id: ADF6B4A4E
title: Brief Offering Prayer to the Oath-Bound Vajrasādhu
type: translation
pechas:
- I17A16122
- I0942A66E
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:06:28.694644
  last_modified_at: 2023-01-04 13:06:28.694650
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I17A16122/0C01: E977
  I0942A66E/1BBB: E977
